trigger:
  - none

pool:
  vmImage: 'ubuntu-latest'

stages:  
- stage: PlanStage
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlanJob
    displayName: 'Terraform Deployment'
    steps:
    - task: TerraformTaskV3@3
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/TerraformTest'
        backendServiceArm: 'POC-NVN ()'
        backendAzureRmResourceGroupName: 'terraform-test'
        backendAzureRmStorageAccountName: 'nvnterraformbackend'
        backendAzureRmContainerName: 'terraformbackend'
        backendAzureRmKey: 'terraform.backend'

    - task: TerraformTaskV3@3
      displayName: 'Terraform Validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(Build.SourcesDirectory)/TerraformTest'

    - script: |
        ls -al $(Build.SourcesDirectory)
      displayName: 'List Files in Sources Directory'

    - task: TerraformTaskV3@3
      displayName: 'Terraform plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(Build.SourcesDirectory)/TerraformTest'
        environmentServiceNameAzureRM: 'POC-NVN'

- stage: ApplyStage
  displayName: 'Terraform Apply'
  jobs:
  - job: waitForValidation
    displayName: Wait for pipeline validation
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: 'naveen.potnuru@programmers.io'
        instructions: 'Please validate the build $(Build.BuildId) configuration and resume'
        onTimeout: 'resume'

  - job: deployAzure
    displayName: deploy infra
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn: [waitForValidation]
    steps:
    - task: TerraformTaskV3@3
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/TerraformTest'
        backendServiceArm: 'POC-NVN'
        backendAzureRmResourceGroupName: 'terraform-test'
        backendAzureRmStorageAccountName: 'nvnterraformbackend'
        backendAzureRmContainerName: 'terraformbackend'
        backendAzureRmKey: 'terraform.backend'

    - task: TerraformTaskV3@3
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(Build.SourcesDirectory)/TerraformTest'
        environmentServiceNameAzureRM: 'POC-NVN'

    - task: TerraformTaskV3@3
      displayName: 'Terraform Apply'
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(Build.SourcesDirectory)/TerraformTest'
        environmentServiceNameAzureRM: 'POC-NVN'

- stage: Destroy
  displayName: 'Terraform Destroy'
  jobs:
  - job: waitForValidation
    displayName: Wait for external validation
    pool: server
    timeoutInMinutes: 4320 # job times out in 3 days
    steps:
    - task: ManualValidation@0
      timeoutInMinutes: 1440 # task times out in 1 day
      inputs:
        notifyUsers: 'naveen.potnuru@programmers.io'
        instructions: 'Please validate the build $(Build.BuildId) configuration and resume'
        onTimeout: 'resume'

  - job: destroyinfra
    displayName: infra destroy
    pool:
      vmImage: 'ubuntu-latest'
    dependsOn: [waitForValidation]
    steps:
    - task: TerraformTaskV3@3
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(Build.SourcesDirectory)/TerraformTest'
        backendServiceArm: 'POC-NVN'
        backendAzureRmResourceGroupName: 'terraform-test'
        backendAzureRmStorageAccountName: 'nvnterraformbackend'
        backendAzureRmContainerName: 'terraformbackend'
        backendAzureRmKey: 'terraform.backend'

    - task: TerraformTaskV3@3
      displayName: 'Terraform Plan'
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(Build.SourcesDirectory)/TerraformTest'
        environmentServiceNameAzureRM: 'POC-NVN'


    - task: TerraformTaskV3@3
      displayName: 'Terraform Destroy'
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(Build.SourcesDirectory)/TerraformTest'
        environmentServiceNameAzureRM: 'POC-NVN'